# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'SOS' do

platform :ios, '7.0'
pod 'DCPathButton', '~> 2.1.3'
pod 'TGCameraViewController'

end

